# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# circle ci docker files
# https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node

version: 2

machine: 
  services: 
    - docker 

#############################################################
# Shared jobs and configuration
#############################################################
enterprise_setup: &enterprise_setup  

attach_workspace_step: &attach_workspace_step
  attach_workspace:
    at: '.'

persist_workspace_step: &persist_workspace_step
  persist_to_workspace:
    root: '.'
    paths: [ '.' ]
    


#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - install_dependencies 
      - build:
          requires: [install_dependencies]
      # - linting:
      #     requires: [install_dependencies]    
      # - e2e_tests:
      #     requires: [install_dependencies]    
      # - build:
      #     requires: [install_dependencies]

#############################################################
# Define jobs
#############################################################
jobs:
  install_dependencies:
    docker:
      - image: circleci/node:8.10-browsers
    steps:
      - checkout
      - restore_cache:
          # key: afs-{{ checksum "package-lock.json" }}
          paths: /home/circleci/node_modules
      - run: npm install --no-progress
      - save_cache:
          # key: afs-{{ checksum "package-lock.json" }} 
          paths: /home/circleci/node_modules
      - *persist_workspace_step

  build:
    docker:
      - image: circleci/node:8.10-browsers
    steps:
      - checkout  
      - *attach_workspace_step  
      - run: npm run build

  linting:
    docker:
      - image: circleci/node:8.10-browsers
    steps:
      - checkout
      - *attach_workspace_step     
      - run: npm run lint

  e2e_tests:
    docker:
      - image: circleci/node:8.10-browsers
    steps:   
      - checkout
      - *attach_workspace_step  
      - run: npm run e2e

# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       - image: circleci/node:8-browsers

#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run lint
#       - run: npm run e2e

  